name: Scheduler

on:
    schedule:
        - cron: '*/30 * * * *' # Every 30 minutes
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
                  cache: 'npm'

            - name: install
              run: npm ci

            - name: Check workload
              id: check
              run: |
                  WORKLOAD=$(npm run --silent update:workload)
                  echo "work=$WORKLOAD" >> "$GITHUB_OUTPUT"

    catalog:
        needs: check
        if: needs.check.outputs.work != '[]'
        uses: ./.github/workflows/catalog.yml
